config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'users/index', to: 'users#index'
  get 'auth/spotify/callback', to: 'users#sync_profile'
  delete 'users/signout', to: 'users#destroy'
  get 'artists/match', to: 'artists#match'
  get 'artists/playlist', to: 'artists#playlist'
  post 'artists/save', to: 'artists#save_track'

end

app/models/artist.rb
class Artist
  include Neo4j::ActiveNode

  property :name, type: String
  property :popularity, type: Integer

  has_many :in, :users, origin: :artists
end

app/models/listens_to.rb
class ListensTo
  include Neo4j::ActiveRel

  from_class :User
  to_class :Artist

  property :artist_presence, type: Integer, default: 0

  def increment_artist_presence
    self.artist_presence += 1
    self.save
  end

  def reset_artist_presence
    self.artist_presence = 0
    self.save
  end
end

app/models/user.rb
class User
  include Neo4j::ActiveNode

  property :email, type: String
  property :username, type: String
  property :display_name, type: String
  property :image_url, type: String

  has_many :out, :artists, rel_class: ListensTo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include ArtistsHelper
  include RspotifyHelper
  include RecommendationHelper

  def match
  end

  def playlist
    recommended_users = recommend_users(current_user)
    retrieve_spotify_users_and_artists(current_user, recommended_users)
  end

  def save_track
    current_spotify_user = retrieve_spotify_user(current_user)
    spotify_track = retrieve_spotify_track(params[:track_id])
    current_spotify_user.save_tracks!([spotify_track])
    redirect_to '/artists/playlist'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  include RspotifyHelper

  def index
  end

  def sync_profile
    current_spotify_user = instantiate_spotify_user(request.env['omniauth.auth'])
    current_database_user = save_users(current_spotify_user)
    save_artists(current_spotify_user, current_database_user)
    session[:user_id] = current_database_user.id
    redirect_to '/artists/match'
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Signed out from Grape successully. Please note you are still signed in to Spotify.'
    redirect_to '/users/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def retrieve_spotify_users_and_artists(current_user, recommended_users)
    @recommended_spotify_users = Array.new
    @recommended_spotify_artists = Hash.new
    recommended_users.each do |recommended_user|
      @recommended_spotify_users << retrieve_spotify_user(recommended_user[0])
      @recommended_spotify_artists[recommended_user[0].username] = Array.new
      recommend_artists(current_user, recommended_user[0]).each do |artist|
        @recommended_spotify_artists[recommended_user[0].username] << retrieve_spotify_artist(artist).first if artist.name != ""
      end
    end
  end

  def artists_from_recommended_user(index)
    @recommended_spotify_artists[@recommended_spotify_users[index].id] if @recommended_spotify_users[index]
  end

  def find_random_track(artists, index)
    artists[index].albums.first.tracks.shuffle.first
  end
end

app/helpers/recommendation_helper.rb
module RecommendationHelper
  # Recommend users
  # ranked by number of shared artists with current user and
  # number of appearance of each shared artist in both recommended user's and current user's playlists
  # capped at 3 recommended users
  def recommend_users(user)
    user.as(:u1).artists.users(:u2).
      where('u2 <> u1').
      order('sum(rel1.artist_presence) + sum(rel2.artist_presence) DESC').
      limit(3).
      pluck('u2', 'sum(rel1.artist_presence)', 'sum(rel2.artist_presence)')
  end

  # Recommend artists (from each recommended user above)
  # who appear in recommended user's but not current user's playlists,
  # ranked by number of appearance in the recommended user's account
  # capped at 10 recommended artists
  def recommend_artists(current_user, recommended_user)
    recommended_artists = Array.new
    artists = retrieve_favourite_artists(recommended_user)
    artists.each do |artist|
      unless current_user.artists.to_a.include?(artist[0]) || recommended_artists.length >= 10
        recommended_artists << artist[0]
      end
    end
    recommended_artists
  end

  private

  def retrieve_favourite_artists(user)
    user.artists(:a).
      order('rel1.artist_presence DESC').
      limit(20).
      pluck('a', 'count(*)', 'rel1')
  end
end

app/helpers/rspotify_helper.rb
module RspotifyHelper
  def instantiate_spotify_user(omniauth_params)
    RSpotify::User.new(omniauth_params)
  end

  def retrieve_spotify_user(user)
    RSpotify::User.find(user.username)
  end

  def retrieve_spotify_artist(artist)
    RSpotify::Artist.search(artist.name)
  end

  def retrieve_spotify_track(track_id)
    RSpotify::Track.find(track_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def save_users(spotify_user)
    database_user = User.merge(email: spotify_user.email, username: spotify_user.id)
    database_user.display_name = spotify_user.display_name if spotify_user.display_name
    database_user.image_url = spotify_user.images.first['url'] if spotify_user.images.first
    database_user.save
    database_user
  end

  def save_artists(spotify_user, database_user)
    reset_all_artist_presence(database_user)
    spotify_user.playlists.each do |playlist|
      playlist.tracks.each do |track|
        track.artists.each do |artist|
          database_artist = Artist.merge(name: artist.name)
          database_artist.popularity = artist.popularity if artist.popularity
          database_artist.save
          save_association(database_user, database_artist)
        end
      end
    end
  end

  def save_association(user, artist)
    if user.artists.include?(artist)
      listens_to = user.artists.first_rel_to(artist)
    else
      listens_to = ListensTo.create(from_node: user, to_node: artist)
    end
    listens_to.increment_artist_presence
  end

  private

  def reset_all_artist_presence(user)
    user.artists.each_rel do |rel|
      rel.reset_artist_presence
    end
  end
end

app/views/artists/_welcome_bar.html.erb
<div class="welcome_bar">
  <%= link_to image_tag("/images/cropped_grape_logo_shadowed.png", :width => 130, :height => 130), '/users/index', id:"welcome_logo", method: :get %>
  <div id="user_img">
    <% if current_user.image_url %>
      <%= link_to image_tag(current_user.image_url, :width => 100, :height => 100, :class => "img_circle"), 'spotify:user:' + current_user.username, :target => "_blank" %>
    <% end %>
  </div>

  <div id="welcome_box">
    <div style="display:block">
      Welcome,
      <% if current_user.display_name == nil %>
        <% name = current_user.username %>
      <% else %>
        <% name = current_user.display_name.split(" ").first %>
      <% end %>
      <%= link_to name, "spotify:user:" + current_user.username, id:"name_link" %>
    </div>
    <%= link_to 'Sign out', '/users/signout', class:"sign_out_welcome link", id:"welcome_sign_out", method: :delete %>
  </div>
</div>

app/views/artists/match.html.erb
<%= render "welcome_bar" %>

<div class="central button_box" id="generate_playlist_box">
  <div id="intro_text">
    Click below to
  </div>
  <%= link_to 'generate a playlist', '/artists/playlist', class:"link", id:"generate_playlist", method: :get %>
</div>

app/views/artists/playlist.html.erb
<%= render "welcome_bar" %>

<% x = 0 %>
<div id ="carousel-example-generic" class="carousel slide" data-interval="false">
  <div class="carousel-inner" role="listbox">
    <% for x in 0..2 %>
      <% artists_array = artists_from_recommended_user(x) %>
      <% if artists_array %>
        <% if x == 0 %>
          <div class="item active">
        <% else %>
          <div class="item">
        <% end %>
          <div>
            <div class="playlist_header">
              <span class="playlist_header_column" id="title_header">Title</span><span class="playlist_header_column" id="artist_header">Artist</span><span class="playlist_header_column" id="genre_header">Genre</span>
            </div>
            <div class="panel-group playlist_area" id="accordion" role="tablist" aria-multiselectable="true">
              <% i = 0 %>
              <% while (artists_array.length - i > 0) && (i < 8) %>
                <% track = find_random_track(artists_array, i) %>
                <div class="panel panel-default">
                  <div class="panel-heading" role="tab" id="heading<%= x %><%= i %>">
                    <h4 class="panel-title">
                      <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= x %><%= i %>" aria-expanded="true" aria-controls="collapse<%= x %><%= i %>">
                        <span class="playlist_item" id="playlist_title"><%= track.name %></span><span class="playlist_item" id="playlist_artist"><%= artists_array[i].name %></span><span class="playlist_item" id="playlist_genre"><%= artists_array[i].genres[0] %></span>
                      </a>
                    </h4>
                  </div>
                  <div id="collapse<%= x %><%= i %>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading<%= x %><%= i %>">
                    <div class="panel-body">
                      <div class="preview_and_save_track_box">
                        <iframe src="https://embed.spotify.com/?uri=<%= track.uri %>" width="80px" height="80" frameborder="0" allowtransparency="true"></iframe>
                        <% if retrieve_spotify_user(current_user).saved_tracks?([track]).first %>
                          <span class="glyphicon glyphicon-ok" id="glyphicon_pos"></span><span id="saved_position">Track already saved</span>
                        <% else %>
                          <%= link_to "Save Track", artists_save_path({track_id: track.id}).to_param, class:"save_track_link", method: :post, remote: :true %>
                        <% end %>
                      </div>
                      <iframe class="follow_artist" src="https://embed.spotify.com/follow/1/?uri=<%= artists_array[i].uri %>" width="300" height="56" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>
                      <%= link_to "More from this artist", "spotify:artist:" + artists_array[i].uri, :id => "artist_page_link" %>
                    </div>
                  </div>
                </div>
                <% i += 1 %>
              <% end %>
            </div>

           <div class="recom_user">
             <div id="recom_user_box">
               This playlist was generated using
               <% if @recommended_spotify_users[x].display_name == nil %>
                 <% name = @recommended_spotify_users[x].id %>
               <% else %>
                 <% name = @recommended_spotify_users[x].display_name.split(" ").first %>
               <% end %>
               <%= link_to name, "spotify:user:" + @recommended_spotify_users[x].id, :id => "name_link" %>'s Spotify
             </div>
             <% if @recommended_spotify_users[x].images.first != nil %>
               <%= link_to image_tag(@recommended_spotify_users[x].images.first['url'], :width => 100, :height => 100, :class => "img_circle", :id => "recom_user_img"), "spotify:user:" + @recommended_spotify_users[x].id %>
             <% end %>
             <div id="follow_button">
               <% user_id = @recommended_spotify_users[x].id %>
               <iframe src="https://embed.spotify.com/follow/1/?uri=spotify:user:<%=user_id%>&size=basic&theme=light" width="200" height="25" scrolling="no" frameborder="0" style="border:none; overflow:hidden;" allowtransparency="true"></iframe>
             </div>
           </div>
          </div>
        </div>
      <% end %>
      <% x += 1 %>
    <% end %>
  </div>


  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicDiscover</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/users/_grape_animation.html.erb
<div class="leaf_fill"></div>
<div class="grape_fill" id="grape_0"></div>
<div class="grape_fill" id="grape_1"></div>
<div class="grape_fill" id="grape_2"></div>
<div class="grape_fill" id="grape_3"></div>
<div class="grape_fill" id="grape_4"></div>
<div class="grape_fill" id="grape_5"></div>
<div class="grape_fill" id="grape_6"></div>
<div class="grape_fill" id="grape_7"></div>

app/views/users/index.html.erb
<body style="height:1000px">
  <% if current_user %>

    <div id="user_img">
      <% if current_user.image_url %>
        <%= link_to image_tag(current_user.image_url, :width => 100, :height => 100, :class => "img_circle"), 'spotify:user:' + current_user.username %>
      <% end %>
    </div>

    <div id="welcome_box">
      Welcome,
      <% if current_user.display_name == nil %>
        <% name = current_user.username %>
      <% else %>
        <% name = current_user.display_name.split(" ").first %>
      <% end %>
      <%= link_to name, 'spotify:user:' + current_user.username, id:"name_link" %>
    </div>
  <% end %>

  <div class="central">
    <div id="logo_box">
      <%= render "grape_animation" %>
      <img src="/images/cropped_grape_logo_shadowed.png" id="index_logo">
      <div class="button_box" id="sign_in_box">
        <% if current_user %>
          <%= link_to 'Generate a playlist', '/artists/playlist', class:"link", id:"generate_playlist", method: :get %>
          <div class="button_divide"></div>
          <%= link_to 'Sign out', '/users/signout', class:"button_box link", id:"sign_out_index", method: :delete %>
        <% else %>
          <%= link_to 'Sign in to Grape with Spotify', '/auth/spotify', class:"link", id:"sign_in"%>
        <% end %>
      </div>
      <% if notice %>
        <div class="sign_out_notice"><%= notice %></div>
      <% end %>
    </div>
    <div id="about_text">
      Grape matches you with people from all over the world who share your music taste. We will find you a user with similar music in their Spotify library, and generate a playlist especially tailored for you based on their favourite music that you don't have.
    </div>
  </div>
</body>